<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="56" ignored="0" total="62" passed="6">
  <reporter-output>
    <line>
      <![CDATA[onStart Suite - About to begin executing Suite MultiBrowser]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : BaseTestSuite.beforeSuite]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : BaseTestSuite.beforeSuite]]>
    </line>
    <line>
      <![CDATA[onStart Test - About to begin executing Test set Chorme Browser]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.beforeTest]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.beforeTest]]>
    </line>
    <line>
      <![CDATA[onStart Test - About to begin executing Test set Firefox Browser]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.beforeTest]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.beforeTest]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : BaseTestSuite.beforeClass]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : BaseTestSuite.beforeClass]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.windowTitle]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.windowTitle]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : BaseTestSuite.beforeClass]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : BaseTestSuite.beforeClass]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.windowTitle]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.windowTitle]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.languageSwitcher]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.languageSwitcher]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.Heading]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.Heading]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.contactSupport]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.contactSupport]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.subHeading]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.subHeading]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.emailPlaceHolder]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.emailPlaceHolder]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.loginButton]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.loginButton]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.onbaordingSideBar]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.onbaordingSideBar]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.errorMessage]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.errorMessage]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.errorMessage]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.errorMessage]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.errorMessage]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.errorMessage]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.enterEmail]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.enterEmail]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Pass]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.googleAuthHeading]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.googleAuthHeading]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.googleAuthButton]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.googleAuthButton]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.googleAuthSkipButton]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.googleAuthSkipButton]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.googleAuthSubHeading]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.googleAuthSubHeading]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.googleAuthNote]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.googleAuthNote]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.languageSwitcher]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.languageSwitcher]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.Heading]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.Heading]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.clickSkipGoogleAuth]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.clickSkipGoogleAuth]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.contactSupport]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.contactSupport]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.subHeading]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.subHeading]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.emailPlaceHolder]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.emailPlaceHolder]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Pass]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.otpHeading]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.otpHeading]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.loginButton]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.loginButton]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.onbaordingSideBar]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.onbaordingSideBar]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.errorMessage]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.errorMessage]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.otpSubHeading]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.otpSubHeading]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.errorMessage]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.errorMessage]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.errorMessage]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.errorMessage]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.enterEmail]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.enterEmail]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Pass]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.googleAuthHeading]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.googleAuthHeading]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.googleAuthButton]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.googleAuthButton]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.otpPlaceHolder]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.otpPlaceHolder]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.googleAuthSkipButton]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.googleAuthSkipButton]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.googleAuthSubHeading]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.googleAuthSubHeading]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.googleAuthNote]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.resendOtpText]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.resendOtpText]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.googleAuthNote]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.clickSkipGoogleAuth]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.clickSkipGoogleAuth]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Pass]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.otpHeading]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.otpHeading]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.otpSubHeading]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.otpSubHeading]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.resendOtpHook]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.resendOtpHook]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.otpPlaceHolder]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.otpPlaceHolder]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.resendOtpText]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.resendOtpText]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.resendOtpHook]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.resendOtpHook]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.resendOtpHookClicked]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.resendOtpHookClicked]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.resendOtpHookClicked]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.resendOtpHookClicked]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.checkEditButton]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.checkEditButton]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.checkEditButton]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.checkEditButton]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.verifyButton]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.verifyButton]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.otpErrorMessage]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.verifyButton]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.verifyButton]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.otpErrorMessage]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.otpErrorMessage]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.otpErrorMessage]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.otpErrorMessage]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.otpErrorMessage]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.otpErrorMessage]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.otpErrorMessage]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.otpErrorMessage]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.otpErrorMessage]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.otpErrorMessage1]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.otpErrorMessage]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.otpErrorMessage1]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.enterOTP]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.enterOTP]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.otpErrorMessage]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Pass]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.otpErrorMessage1]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.otpErrorMessage1]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Failed]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.enterOTP]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.enterOTP]]>
    </line>
    <line>
      <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
    </line>
    <line>
      <![CDATA[Test Status: Pass]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.afterClass]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.afterClass]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : BaseTestSuite.afterTest]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : BaseTestSuite.afterTest]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.afterClass]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.afterClass]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : BaseTestSuite.afterTest]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : BaseTestSuite.afterTest]]>
    </line>
    <line>
      <![CDATA[beforeInvocation - About to begin executing following method : BaseTestSuite.afterSuite]]>
    </line>
    <line>
      <![CDATA[afterIncovation - Completed executing following method : BaseTestSuite.afterSuite]]>
    </line>
  </reporter-output>
  <suite name="MultiBrowser" duration-ms="107316" started-at="2017-06-20T10:41:14Z" finished-at="2017-06-20T10:43:01Z">
    <groups>
    </groups>
    <test name="Chorme Browser" duration-ms="104687" started-at="2017-06-20T10:41:14Z" finished-at="2017-06-20T10:42:58Z">
      <class name="SignIn.FlockSignIn">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:SignIn.FlockSignIn@343f4d3d]" name="beforeSuite" is-config="true" duration-ms="19" started-at="2017-06-20T16:11:14Z" finished-at="2017-06-20T16:11:14Z">
          <reporter-output>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : BaseTestSuite.beforeSuite]]>
            </line>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:SignIn.FlockSignIn@343f4d3d]" name="beforeTest" is-config="true" duration-ms="1206" started-at="2017-06-20T16:11:14Z" finished-at="2017-06-20T16:11:15Z">
          <reporter-output>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.beforeTest]]>
            </line>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="beforeClass(java.lang.String)[pri:0, instance:SignIn.FlockSignIn@343f4d3d]" name="beforeClass" is-config="true" duration-ms="53257" started-at="2017-06-20T16:11:15Z" finished-at="2017-06-20T16:12:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : BaseTestSuite.beforeClass]]>
            </line>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="windowTitle()[pri:0, instance:SignIn.FlockSignIn@343f4d3d]" name="windowTitle" duration-ms="8" started-at="2017-06-20T16:12:08Z" finished-at="2017-06-20T16:12:08Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.getTitle(GenericMethods.java:121)
	at SignIn.FlockSignIn.windowTitle(FlockSignIn.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.windowTitle]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.windowTitle]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- windowTitle -->
        <test-method status="FAIL" signature="languageSwitcher()[pri:1, instance:SignIn.FlockSignIn@343f4d3d]" name="languageSwitcher" duration-ms="6" started-at="2017-06-20T16:12:24Z" finished-at="2017-06-20T16:12:24Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.implicitWait(GenericMethods.java:213)
	at SignIn.FlockSignIn.languageSwitcher(FlockSignIn.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.languageSwitcher]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.languageSwitcher]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- languageSwitcher -->
        <test-method status="FAIL" signature="Heading()[pri:2, instance:SignIn.FlockSignIn@343f4d3d]" name="Heading" duration-ms="5" started-at="2017-06-20T16:12:24Z" finished-at="2017-06-20T16:12:24Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.implicitWait(GenericMethods.java:213)
	at SignIn.FlockSignIn.Heading(FlockSignIn.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.Heading]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.Heading]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- Heading -->
        <test-method status="FAIL" signature="contactSupport()[pri:3, instance:SignIn.FlockSignIn@343f4d3d]" name="contactSupport" duration-ms="3" started-at="2017-06-20T16:12:25Z" finished-at="2017-06-20T16:12:25Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementDisplayed(GenericMethods.java:156)
	at SignIn.FlockSignIn.contactSupport(FlockSignIn.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.contactSupport]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.contactSupport]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- contactSupport -->
        <test-method status="FAIL" signature="subHeading()[pri:4, instance:SignIn.FlockSignIn@343f4d3d]" name="subHeading" duration-ms="1" started-at="2017-06-20T16:12:25Z" finished-at="2017-06-20T16:12:25Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementDisplayed(GenericMethods.java:156)
	at SignIn.FlockSignIn.subHeading(FlockSignIn.java:179)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.subHeading]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.subHeading]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- subHeading -->
        <test-method status="FAIL" signature="emailPlaceHolder()[pri:5, instance:SignIn.FlockSignIn@343f4d3d]" name="emailPlaceHolder" duration-ms="1" started-at="2017-06-20T16:12:26Z" finished-at="2017-06-20T16:12:26Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementDisplayed(GenericMethods.java:156)
	at SignIn.FlockSignIn.emailPlaceHolder(FlockSignIn.java:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.emailPlaceHolder]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.emailPlaceHolder]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- emailPlaceHolder -->
        <test-method status="FAIL" signature="loginButton()[pri:6, instance:SignIn.FlockSignIn@343f4d3d]" name="loginButton" duration-ms="1" started-at="2017-06-20T16:12:26Z" finished-at="2017-06-20T16:12:26Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementDisplayed(GenericMethods.java:156)
	at SignIn.FlockSignIn.loginButton(FlockSignIn.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.loginButton]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.loginButton]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginButton -->
        <test-method status="FAIL" signature="onbaordingSideBar()[pri:7, instance:SignIn.FlockSignIn@343f4d3d]" name="onbaordingSideBar" duration-ms="2" started-at="2017-06-20T16:12:27Z" finished-at="2017-06-20T16:12:27Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementDisplayed(GenericMethods.java:156)
	at SignIn.FlockSignIn.onbaordingSideBar(FlockSignIn.java:200)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.onbaordingSideBar]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.onbaordingSideBar]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- onbaordingSideBar -->
        <test-method status="FAIL" signature="errorMessage(java.lang.String)[pri:8, instance:SignIn.FlockSignIn@343f4d3d]" name="errorMessage" duration-ms="2" started-at="2017-06-20T16:12:28Z" data-provider="emails" finished-at="2017-06-20T16:12:28Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementIsDisplayed(GenericMethods.java:167)
	at SignIn.FlockSignIn.errorMessage(FlockSignIn.java:208)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.errorMessage]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.errorMessage]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- errorMessage -->
        <test-method status="FAIL" signature="errorMessage(java.lang.String)[pri:8, instance:SignIn.FlockSignIn@343f4d3d]" name="errorMessage" duration-ms="2" started-at="2017-06-20T16:12:28Z" data-provider="emails" finished-at="2017-06-20T16:12:28Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[jffhfhfh]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementIsDisplayed(GenericMethods.java:167)
	at SignIn.FlockSignIn.errorMessage(FlockSignIn.java:208)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.errorMessage]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.errorMessage]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- errorMessage -->
        <test-method status="FAIL" signature="errorMessage(java.lang.String)[pri:8, instance:SignIn.FlockSignIn@343f4d3d]" name="errorMessage" duration-ms="5" started-at="2017-06-20T16:12:28Z" data-provider="emails" finished-at="2017-06-20T16:12:28Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[jffhfhfh@jdjdjjdj]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementIsDisplayed(GenericMethods.java:167)
	at SignIn.FlockSignIn.errorMessage(FlockSignIn.java:208)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.errorMessage]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.errorMessage]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- errorMessage -->
        <test-method status="PASS" signature="enterEmail()[pri:9, instance:SignIn.FlockSignIn@343f4d3d]" name="enterEmail" duration-ms="2" started-at="2017-06-20T16:12:29Z" finished-at="2017-06-20T16:12:29Z">
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.enterEmail]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.enterEmail]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Pass]]>
            </line>
          </reporter-output>
        </test-method> <!-- enterEmail -->
        <test-method status="FAIL" signature="googleAuthHeading()[pri:10, instance:SignIn.FlockSignIn@343f4d3d]" name="googleAuthHeading" duration-ms="1" started-at="2017-06-20T16:12:30Z" finished-at="2017-06-20T16:12:30Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.implicitWait(GenericMethods.java:213)
	at SignIn.FlockSignIn.googleAuthHeading(FlockSignIn.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.googleAuthHeading]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.googleAuthHeading]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- googleAuthHeading -->
        <test-method status="FAIL" signature="googleAuthButton()[pri:11, instance:SignIn.FlockSignIn@343f4d3d]" name="googleAuthButton" duration-ms="1" started-at="2017-06-20T16:12:30Z" finished-at="2017-06-20T16:12:30Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementDisplayed(GenericMethods.java:156)
	at SignIn.FlockSignIn.googleAuthButton(FlockSignIn.java:237)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.googleAuthButton]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.googleAuthButton]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- googleAuthButton -->
        <test-method status="FAIL" signature="googleAuthSkipButton()[pri:11, instance:SignIn.FlockSignIn@343f4d3d]" name="googleAuthSkipButton" duration-ms="1" started-at="2017-06-20T16:12:30Z" finished-at="2017-06-20T16:12:31Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementDisplayed(GenericMethods.java:156)
	at SignIn.FlockSignIn.googleAuthSkipButton(FlockSignIn.java:244)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.googleAuthSkipButton]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.googleAuthSkipButton]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- googleAuthSkipButton -->
        <test-method status="FAIL" signature="googleAuthSubHeading()[pri:11, instance:SignIn.FlockSignIn@343f4d3d]" name="googleAuthSubHeading" duration-ms="1" started-at="2017-06-20T16:12:31Z" finished-at="2017-06-20T16:12:31Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementDisplayed(GenericMethods.java:156)
	at SignIn.FlockSignIn.googleAuthSubHeading(FlockSignIn.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.googleAuthSubHeading]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.googleAuthSubHeading]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- googleAuthSubHeading -->
        <test-method status="FAIL" signature="googleAuthNote()[pri:12, instance:SignIn.FlockSignIn@343f4d3d]" name="googleAuthNote" duration-ms="5" started-at="2017-06-20T16:12:31Z" finished-at="2017-06-20T16:12:31Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementDisplayed(GenericMethods.java:156)
	at SignIn.FlockSignIn.googleAuthNote(FlockSignIn.java:251)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.googleAuthNote]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.googleAuthNote]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- googleAuthNote -->
        <test-method status="PASS" signature="clickSkipGoogleAuth()[pri:13, instance:SignIn.FlockSignIn@343f4d3d]" name="clickSkipGoogleAuth" duration-ms="2" started-at="2017-06-20T16:12:32Z" finished-at="2017-06-20T16:12:32Z">
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.clickSkipGoogleAuth]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.clickSkipGoogleAuth]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Pass]]>
            </line>
          </reporter-output>
        </test-method> <!-- clickSkipGoogleAuth -->
        <test-method status="FAIL" signature="otpHeading()[pri:14, instance:SignIn.FlockSignIn@343f4d3d]" name="otpHeading" duration-ms="2" started-at="2017-06-20T16:12:32Z" finished-at="2017-06-20T16:12:32Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.implicitWait(GenericMethods.java:213)
	at SignIn.FlockSignIn.otpHeading(FlockSignIn.java:263)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.otpHeading]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.otpHeading]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- otpHeading -->
        <test-method status="FAIL" signature="otpSubHeading()[pri:15, instance:SignIn.FlockSignIn@343f4d3d]" name="otpSubHeading" duration-ms="5" started-at="2017-06-20T16:12:33Z" finished-at="2017-06-20T16:12:33Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementDisplayed(GenericMethods.java:156)
	at SignIn.FlockSignIn.otpSubHeading(FlockSignIn.java:272)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.otpSubHeading]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.otpSubHeading]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- otpSubHeading -->
        <test-method status="FAIL" signature="otpPlaceHolder()[pri:16, instance:SignIn.FlockSignIn@343f4d3d]" name="otpPlaceHolder" duration-ms="1" started-at="2017-06-20T16:12:33Z" finished-at="2017-06-20T16:12:33Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementDisplayed(GenericMethods.java:156)
	at SignIn.FlockSignIn.otpPlaceHolder(FlockSignIn.java:279)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.otpPlaceHolder]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.otpPlaceHolder]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- otpPlaceHolder -->
        <test-method status="FAIL" signature="resendOtpText()[pri:17, instance:SignIn.FlockSignIn@343f4d3d]" name="resendOtpText" duration-ms="2" started-at="2017-06-20T16:12:34Z" finished-at="2017-06-20T16:12:34Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementDisplayed(GenericMethods.java:156)
	at SignIn.FlockSignIn.resendOtpText(FlockSignIn.java:286)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.resendOtpText]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.resendOtpText]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- resendOtpText -->
        <test-method status="FAIL" signature="resendOtpHook()[pri:18, instance:SignIn.FlockSignIn@343f4d3d]" name="resendOtpHook" duration-ms="1" started-at="2017-06-20T16:12:34Z" finished-at="2017-06-20T16:12:34Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementDisplayed(GenericMethods.java:156)
	at SignIn.FlockSignIn.resendOtpHook(FlockSignIn.java:293)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.resendOtpHook]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.resendOtpHook]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- resendOtpHook -->
        <test-method status="FAIL" signature="resendOtpHookClicked()[pri:19, instance:SignIn.FlockSignIn@343f4d3d]" name="resendOtpHookClicked" duration-ms="2" started-at="2017-06-20T16:12:35Z" finished-at="2017-06-20T16:12:35Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementDisplayed(GenericMethods.java:156)
	at SignIn.FlockSignIn.resendOtpHookClicked(FlockSignIn.java:301)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.resendOtpHookClicked]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.resendOtpHookClicked]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- resendOtpHookClicked -->
        <test-method status="FAIL" signature="checkEditButton()[pri:20, instance:SignIn.FlockSignIn@343f4d3d]" name="checkEditButton" duration-ms="1" started-at="2017-06-20T16:12:35Z" finished-at="2017-06-20T16:12:35Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementDisplayed(GenericMethods.java:156)
	at SignIn.FlockSignIn.checkEditButton(FlockSignIn.java:315)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.checkEditButton]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.checkEditButton]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- checkEditButton -->
        <test-method status="FAIL" signature="verifyButton()[pri:20, instance:SignIn.FlockSignIn@343f4d3d]" name="verifyButton" duration-ms="2" started-at="2017-06-20T16:12:36Z" finished-at="2017-06-20T16:12:36Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementDisplayed(GenericMethods.java:156)
	at SignIn.FlockSignIn.verifyButton(FlockSignIn.java:308)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.verifyButton]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.verifyButton]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- verifyButton -->
        <test-method status="FAIL" signature="otpErrorMessage(java.lang.String)[pri:21, instance:SignIn.FlockSignIn@343f4d3d]" name="otpErrorMessage" duration-ms="2003" started-at="2017-06-20T16:12:36Z" data-provider="otp" finished-at="2017-06-20T16:12:38Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementIsDisplayed(GenericMethods.java:167)
	at SignIn.FlockSignIn.otpErrorMessage(FlockSignIn.java:331)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.otpErrorMessage]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.otpErrorMessage]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- otpErrorMessage -->
        <test-method status="FAIL" signature="otpErrorMessage(java.lang.String)[pri:21, instance:SignIn.FlockSignIn@343f4d3d]" name="otpErrorMessage" duration-ms="2003" started-at="2017-06-20T16:12:39Z" data-provider="otp" finished-at="2017-06-20T16:12:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[jffhfh]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementIsDisplayed(GenericMethods.java:167)
	at SignIn.FlockSignIn.otpErrorMessage(FlockSignIn.java:331)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.otpErrorMessage]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.otpErrorMessage]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- otpErrorMessage -->
        <test-method status="FAIL" signature="otpErrorMessage(java.lang.String)[pri:21, instance:SignIn.FlockSignIn@343f4d3d]" name="otpErrorMessage" duration-ms="2004" started-at="2017-06-20T16:12:41Z" data-provider="otp" finished-at="2017-06-20T16:12:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[1q2q3q]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementIsDisplayed(GenericMethods.java:167)
	at SignIn.FlockSignIn.otpErrorMessage(FlockSignIn.java:331)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.otpErrorMessage]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.otpErrorMessage]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- otpErrorMessage -->
        <test-method status="FAIL" signature="otpErrorMessage1()[pri:22, instance:SignIn.FlockSignIn@343f4d3d]" name="otpErrorMessage1" duration-ms="2013" started-at="2017-06-20T16:12:44Z" finished-at="2017-06-20T16:12:46Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementIsDisplayed(GenericMethods.java:167)
	at SignIn.FlockSignIn.otpErrorMessage1(FlockSignIn.java:342)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.otpErrorMessage1]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.otpErrorMessage1]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- otpErrorMessage1 -->
        <test-method status="PASS" signature="enterOTP()[pri:23, instance:SignIn.FlockSignIn@343f4d3d]" name="enterOTP" duration-ms="2" started-at="2017-06-20T16:12:46Z" finished-at="2017-06-20T16:12:46Z">
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.enterOTP]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.enterOTP]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Pass]]>
            </line>
          </reporter-output>
        </test-method> <!-- enterOTP -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:SignIn.FlockSignIn@343f4d3d]" name="afterClass" is-config="true" duration-ms="11959" started-at="2017-06-20T16:12:46Z" finished-at="2017-06-20T16:12:58Z">
          <reporter-output>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.afterClass]]>
            </line>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:SignIn.FlockSignIn@343f4d3d]" name="afterTest" is-config="true" duration-ms="0" started-at="2017-06-20T16:12:58Z" finished-at="2017-06-20T16:12:58Z">
          <reporter-output>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : BaseTestSuite.afterTest]]>
            </line>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:SignIn.FlockSignIn@343f4d3d]" name="afterSuite" is-config="true" duration-ms="1" started-at="2017-06-20T16:13:01Z" finished-at="2017-06-20T16:13:01Z">
          <reporter-output>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : BaseTestSuite.afterSuite]]>
            </line>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- SignIn.FlockSignIn -->
    </test> <!-- Chorme Browser -->
    <test name="Firefox Browser" duration-ms="107316" started-at="2017-06-20T10:41:14Z" finished-at="2017-06-20T10:43:01Z">
      <class name="SignIn.FlockSignIn">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:SignIn.FlockSignIn@3ffc5af1]" name="beforeTest" is-config="true" duration-ms="1207" started-at="2017-06-20T16:11:14Z" finished-at="2017-06-20T16:11:15Z">
          <reporter-output>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.beforeTest]]>
            </line>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="beforeClass(java.lang.String)[pri:0, instance:SignIn.FlockSignIn@3ffc5af1]" name="beforeClass" is-config="true" duration-ms="55748" started-at="2017-06-20T16:11:15Z" finished-at="2017-06-20T16:12:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : BaseTestSuite.beforeClass]]>
            </line>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="windowTitle()[pri:0, instance:SignIn.FlockSignIn@3ffc5af1]" name="windowTitle" duration-ms="8" started-at="2017-06-20T16:12:11Z" finished-at="2017-06-20T16:12:11Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.getTitle(GenericMethods.java:121)
	at SignIn.FlockSignIn.windowTitle(FlockSignIn.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.windowTitle]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.windowTitle]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- windowTitle -->
        <test-method status="FAIL" signature="languageSwitcher()[pri:1, instance:SignIn.FlockSignIn@3ffc5af1]" name="languageSwitcher" duration-ms="5" started-at="2017-06-20T16:12:11Z" finished-at="2017-06-20T16:12:11Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.implicitWait(GenericMethods.java:213)
	at SignIn.FlockSignIn.languageSwitcher(FlockSignIn.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.languageSwitcher]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.languageSwitcher]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- languageSwitcher -->
        <test-method status="FAIL" signature="Heading()[pri:2, instance:SignIn.FlockSignIn@3ffc5af1]" name="Heading" duration-ms="8" started-at="2017-06-20T16:12:11Z" finished-at="2017-06-20T16:12:11Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.implicitWait(GenericMethods.java:213)
	at SignIn.FlockSignIn.Heading(FlockSignIn.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.Heading]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.Heading]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- Heading -->
        <test-method status="FAIL" signature="contactSupport()[pri:3, instance:SignIn.FlockSignIn@3ffc5af1]" name="contactSupport" duration-ms="14" started-at="2017-06-20T16:12:12Z" finished-at="2017-06-20T16:12:12Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementDisplayed(GenericMethods.java:156)
	at SignIn.FlockSignIn.contactSupport(FlockSignIn.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.contactSupport]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.contactSupport]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- contactSupport -->
        <test-method status="FAIL" signature="subHeading()[pri:4, instance:SignIn.FlockSignIn@3ffc5af1]" name="subHeading" duration-ms="3" started-at="2017-06-20T16:12:13Z" finished-at="2017-06-20T16:12:13Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementDisplayed(GenericMethods.java:156)
	at SignIn.FlockSignIn.subHeading(FlockSignIn.java:179)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.subHeading]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.subHeading]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- subHeading -->
        <test-method status="FAIL" signature="emailPlaceHolder()[pri:5, instance:SignIn.FlockSignIn@3ffc5af1]" name="emailPlaceHolder" duration-ms="1" started-at="2017-06-20T16:12:14Z" finished-at="2017-06-20T16:12:14Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementDisplayed(GenericMethods.java:156)
	at SignIn.FlockSignIn.emailPlaceHolder(FlockSignIn.java:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.emailPlaceHolder]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.emailPlaceHolder]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- emailPlaceHolder -->
        <test-method status="FAIL" signature="loginButton()[pri:6, instance:SignIn.FlockSignIn@3ffc5af1]" name="loginButton" duration-ms="3" started-at="2017-06-20T16:12:15Z" finished-at="2017-06-20T16:12:15Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementDisplayed(GenericMethods.java:156)
	at SignIn.FlockSignIn.loginButton(FlockSignIn.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.loginButton]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.loginButton]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginButton -->
        <test-method status="FAIL" signature="onbaordingSideBar()[pri:7, instance:SignIn.FlockSignIn@3ffc5af1]" name="onbaordingSideBar" duration-ms="2" started-at="2017-06-20T16:12:17Z" finished-at="2017-06-20T16:12:17Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementDisplayed(GenericMethods.java:156)
	at SignIn.FlockSignIn.onbaordingSideBar(FlockSignIn.java:200)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.onbaordingSideBar]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.onbaordingSideBar]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- onbaordingSideBar -->
        <test-method status="FAIL" signature="errorMessage(java.lang.String)[pri:8, instance:SignIn.FlockSignIn@3ffc5af1]" name="errorMessage" duration-ms="38" started-at="2017-06-20T16:12:18Z" data-provider="emails" finished-at="2017-06-20T16:12:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementIsDisplayed(GenericMethods.java:167)
	at SignIn.FlockSignIn.errorMessage(FlockSignIn.java:208)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.errorMessage]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.errorMessage]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- errorMessage -->
        <test-method status="FAIL" signature="errorMessage(java.lang.String)[pri:8, instance:SignIn.FlockSignIn@3ffc5af1]" name="errorMessage" duration-ms="3" started-at="2017-06-20T16:12:18Z" data-provider="emails" finished-at="2017-06-20T16:12:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[jffhfhfh]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementIsDisplayed(GenericMethods.java:167)
	at SignIn.FlockSignIn.errorMessage(FlockSignIn.java:208)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.errorMessage]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.errorMessage]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- errorMessage -->
        <test-method status="FAIL" signature="errorMessage(java.lang.String)[pri:8, instance:SignIn.FlockSignIn@3ffc5af1]" name="errorMessage" duration-ms="4" started-at="2017-06-20T16:12:19Z" data-provider="emails" finished-at="2017-06-20T16:12:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[jffhfhfh@jdjdjjdj]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementIsDisplayed(GenericMethods.java:167)
	at SignIn.FlockSignIn.errorMessage(FlockSignIn.java:208)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.errorMessage]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.errorMessage]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- errorMessage -->
        <test-method status="PASS" signature="enterEmail()[pri:9, instance:SignIn.FlockSignIn@3ffc5af1]" name="enterEmail" duration-ms="5" started-at="2017-06-20T16:12:20Z" finished-at="2017-06-20T16:12:20Z">
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.enterEmail]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.enterEmail]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Pass]]>
            </line>
          </reporter-output>
        </test-method> <!-- enterEmail -->
        <test-method status="FAIL" signature="googleAuthHeading()[pri:10, instance:SignIn.FlockSignIn@3ffc5af1]" name="googleAuthHeading" duration-ms="2" started-at="2017-06-20T16:12:20Z" finished-at="2017-06-20T16:12:20Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.implicitWait(GenericMethods.java:213)
	at SignIn.FlockSignIn.googleAuthHeading(FlockSignIn.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.googleAuthHeading]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.googleAuthHeading]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- googleAuthHeading -->
        <test-method status="FAIL" signature="googleAuthButton()[pri:11, instance:SignIn.FlockSignIn@3ffc5af1]" name="googleAuthButton" duration-ms="2" started-at="2017-06-20T16:12:21Z" finished-at="2017-06-20T16:12:21Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementDisplayed(GenericMethods.java:156)
	at SignIn.FlockSignIn.googleAuthButton(FlockSignIn.java:237)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.googleAuthButton]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.googleAuthButton]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- googleAuthButton -->
        <test-method status="FAIL" signature="googleAuthSkipButton()[pri:11, instance:SignIn.FlockSignIn@3ffc5af1]" name="googleAuthSkipButton" duration-ms="3" started-at="2017-06-20T16:12:22Z" finished-at="2017-06-20T16:12:22Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementDisplayed(GenericMethods.java:156)
	at SignIn.FlockSignIn.googleAuthSkipButton(FlockSignIn.java:244)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.googleAuthSkipButton]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.googleAuthSkipButton]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- googleAuthSkipButton -->
        <test-method status="FAIL" signature="googleAuthSubHeading()[pri:11, instance:SignIn.FlockSignIn@3ffc5af1]" name="googleAuthSubHeading" duration-ms="2" started-at="2017-06-20T16:12:23Z" finished-at="2017-06-20T16:12:23Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementDisplayed(GenericMethods.java:156)
	at SignIn.FlockSignIn.googleAuthSubHeading(FlockSignIn.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.googleAuthSubHeading]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.googleAuthSubHeading]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- googleAuthSubHeading -->
        <test-method status="FAIL" signature="googleAuthNote()[pri:12, instance:SignIn.FlockSignIn@3ffc5af1]" name="googleAuthNote" duration-ms="2" started-at="2017-06-20T16:12:23Z" finished-at="2017-06-20T16:12:23Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementDisplayed(GenericMethods.java:156)
	at SignIn.FlockSignIn.googleAuthNote(FlockSignIn.java:251)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.googleAuthNote]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.googleAuthNote]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- googleAuthNote -->
        <test-method status="PASS" signature="clickSkipGoogleAuth()[pri:13, instance:SignIn.FlockSignIn@3ffc5af1]" name="clickSkipGoogleAuth" duration-ms="2" started-at="2017-06-20T16:12:25Z" finished-at="2017-06-20T16:12:25Z">
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.clickSkipGoogleAuth]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.clickSkipGoogleAuth]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Pass]]>
            </line>
          </reporter-output>
        </test-method> <!-- clickSkipGoogleAuth -->
        <test-method status="FAIL" signature="otpHeading()[pri:14, instance:SignIn.FlockSignIn@3ffc5af1]" name="otpHeading" duration-ms="2" started-at="2017-06-20T16:12:26Z" finished-at="2017-06-20T16:12:26Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.implicitWait(GenericMethods.java:213)
	at SignIn.FlockSignIn.otpHeading(FlockSignIn.java:263)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.otpHeading]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.otpHeading]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- otpHeading -->
        <test-method status="FAIL" signature="otpSubHeading()[pri:15, instance:SignIn.FlockSignIn@3ffc5af1]" name="otpSubHeading" duration-ms="3" started-at="2017-06-20T16:12:28Z" finished-at="2017-06-20T16:12:28Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementDisplayed(GenericMethods.java:156)
	at SignIn.FlockSignIn.otpSubHeading(FlockSignIn.java:272)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.otpSubHeading]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.otpSubHeading]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- otpSubHeading -->
        <test-method status="FAIL" signature="otpPlaceHolder()[pri:16, instance:SignIn.FlockSignIn@3ffc5af1]" name="otpPlaceHolder" duration-ms="6" started-at="2017-06-20T16:12:30Z" finished-at="2017-06-20T16:12:30Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementDisplayed(GenericMethods.java:156)
	at SignIn.FlockSignIn.otpPlaceHolder(FlockSignIn.java:279)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.otpPlaceHolder]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.otpPlaceHolder]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- otpPlaceHolder -->
        <test-method status="FAIL" signature="resendOtpText()[pri:17, instance:SignIn.FlockSignIn@3ffc5af1]" name="resendOtpText" duration-ms="4" started-at="2017-06-20T16:12:31Z" finished-at="2017-06-20T16:12:31Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementDisplayed(GenericMethods.java:156)
	at SignIn.FlockSignIn.resendOtpText(FlockSignIn.java:286)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.resendOtpText]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.resendOtpText]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- resendOtpText -->
        <test-method status="FAIL" signature="resendOtpHook()[pri:18, instance:SignIn.FlockSignIn@3ffc5af1]" name="resendOtpHook" duration-ms="2" started-at="2017-06-20T16:12:33Z" finished-at="2017-06-20T16:12:33Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementDisplayed(GenericMethods.java:156)
	at SignIn.FlockSignIn.resendOtpHook(FlockSignIn.java:293)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.resendOtpHook]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.resendOtpHook]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- resendOtpHook -->
        <test-method status="FAIL" signature="resendOtpHookClicked()[pri:19, instance:SignIn.FlockSignIn@3ffc5af1]" name="resendOtpHookClicked" duration-ms="9" started-at="2017-06-20T16:12:34Z" finished-at="2017-06-20T16:12:34Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementDisplayed(GenericMethods.java:156)
	at SignIn.FlockSignIn.resendOtpHookClicked(FlockSignIn.java:301)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.resendOtpHookClicked]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.resendOtpHookClicked]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- resendOtpHookClicked -->
        <test-method status="FAIL" signature="checkEditButton()[pri:20, instance:SignIn.FlockSignIn@3ffc5af1]" name="checkEditButton" duration-ms="1" started-at="2017-06-20T16:12:35Z" finished-at="2017-06-20T16:12:35Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementDisplayed(GenericMethods.java:156)
	at SignIn.FlockSignIn.checkEditButton(FlockSignIn.java:315)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.checkEditButton]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.checkEditButton]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- checkEditButton -->
        <test-method status="FAIL" signature="verifyButton()[pri:20, instance:SignIn.FlockSignIn@3ffc5af1]" name="verifyButton" duration-ms="1" started-at="2017-06-20T16:12:37Z" finished-at="2017-06-20T16:12:37Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementDisplayed(GenericMethods.java:156)
	at SignIn.FlockSignIn.verifyButton(FlockSignIn.java:308)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.verifyButton]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.verifyButton]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- verifyButton -->
        <test-method status="FAIL" signature="otpErrorMessage(java.lang.String)[pri:21, instance:SignIn.FlockSignIn@3ffc5af1]" name="otpErrorMessage" duration-ms="2032" started-at="2017-06-20T16:12:39Z" data-provider="otp" finished-at="2017-06-20T16:12:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementIsDisplayed(GenericMethods.java:167)
	at SignIn.FlockSignIn.otpErrorMessage(FlockSignIn.java:331)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.otpErrorMessage]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.otpErrorMessage]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- otpErrorMessage -->
        <test-method status="FAIL" signature="otpErrorMessage(java.lang.String)[pri:21, instance:SignIn.FlockSignIn@3ffc5af1]" name="otpErrorMessage" duration-ms="2002" started-at="2017-06-20T16:12:41Z" data-provider="otp" finished-at="2017-06-20T16:12:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[jffhfh]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementIsDisplayed(GenericMethods.java:167)
	at SignIn.FlockSignIn.otpErrorMessage(FlockSignIn.java:331)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.otpErrorMessage]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.otpErrorMessage]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- otpErrorMessage -->
        <test-method status="FAIL" signature="otpErrorMessage(java.lang.String)[pri:21, instance:SignIn.FlockSignIn@3ffc5af1]" name="otpErrorMessage" duration-ms="2011" started-at="2017-06-20T16:12:44Z" data-provider="otp" finished-at="2017-06-20T16:12:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[1q2q3q]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementIsDisplayed(GenericMethods.java:167)
	at SignIn.FlockSignIn.otpErrorMessage(FlockSignIn.java:331)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.otpErrorMessage]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.otpErrorMessage]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- otpErrorMessage -->
        <test-method status="FAIL" signature="otpErrorMessage1()[pri:22, instance:SignIn.FlockSignIn@3ffc5af1]" name="otpErrorMessage1" duration-ms="2008" started-at="2017-06-20T16:12:47Z" finished-at="2017-06-20T16:12:49Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.GenericMethods.elementIsDisplayed(GenericMethods.java:167)
	at SignIn.FlockSignIn.otpErrorMessage1(FlockSignIn.java:342)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.otpErrorMessage1]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.otpErrorMessage1]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- otpErrorMessage1 -->
        <test-method status="PASS" signature="enterOTP()[pri:23, instance:SignIn.FlockSignIn@3ffc5af1]" name="enterOTP" duration-ms="2" started-at="2017-06-20T16:12:49Z" finished-at="2017-06-20T16:12:49Z">
          <reporter-output>
            <line>
              <![CDATA[beforeInvocation - About to begin executing following method : FlockSignIn.enterOTP]]>
            </line>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.enterOTP]]>
            </line>
            <line>
              <![CDATA[Test Method resides in SignIn.FlockSignIn]]>
            </line>
            <line>
              <![CDATA[Test Status: Pass]]>
            </line>
          </reporter-output>
        </test-method> <!-- enterOTP -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:SignIn.FlockSignIn@3ffc5af1]" name="afterClass" is-config="true" duration-ms="11065" started-at="2017-06-20T16:12:50Z" finished-at="2017-06-20T16:13:01Z">
          <reporter-output>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : FlockSignIn.afterClass]]>
            </line>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:SignIn.FlockSignIn@3ffc5af1]" name="afterTest" is-config="true" duration-ms="0" started-at="2017-06-20T16:13:01Z" finished-at="2017-06-20T16:13:01Z">
          <reporter-output>
            <line>
              <![CDATA[afterIncovation - Completed executing following method : BaseTestSuite.afterTest]]>
            </line>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- SignIn.FlockSignIn -->
    </test> <!-- Firefox Browser -->
  </suite> <!-- MultiBrowser -->
</testng-results>
